 .gitignore                                         | 482 [32m+++++++++++++++++++++[m
 NovaStore.slnx                                     |   8 [32m+[m
 src/NovaStore.Api/Endpoints/CategoriesEndpoints.cs |  31 [32m++[m
 src/NovaStore.Api/Endpoints/ProductsEndpoints.cs   |  26 [32m++[m
 .../ExceptionHandling/GlobalExceptionHandler.cs    |  72 [32m+++[m
 src/NovaStore.Api/NovaStore.Api.csproj             |  23 [32m+[m
 src/NovaStore.Api/NovaStore.Api.http               |   6 [32m+[m
 src/NovaStore.Api/Program.cs                       |  32 [32m++[m
 src/NovaStore.Api/Properties/launchSettings.json   |  23 [32m+[m
 src/NovaStore.Api/appsettings.Development.json     |   8 [32m+[m
 src/NovaStore.Api/appsettings.json                 |  12 [32m+[m
 .../Categories/Common/CategoryDto.cs               |   8 [32m+[m
 .../Common/CreateCategory/CreateCategoryCommand.cs |   6 [32m+[m
 .../CreateCategory/CreateCategoryCommandHandler.cs | 112 [32m+++++[m
 src/NovaStore.Application/Class1.cs                |   6 [32m+[m
 .../Common/Exceptions/ConflictException.cs         |   9 [32m+[m
 .../Common/Exceptions/ValidationException.cs       |  13 [32m+[m
 .../Common/Interfaces/ICategoryRepository.cs       |  17 [32m+[m
 .../Common/Interfaces/IProductRepository.cs        |   9 [32m+[m
 src/NovaStore.Application/DependencyInjection.cs   |  17 [32m+[m
 .../NovaStore.Application.csproj                   |  17 [32m+[m
 .../Products/Common/ProductDto.cs                  |  16 [32m+[m
 .../Queries/GetProducts/GetProductsQuery.cs        |  37 [32m++[m
 src/NovaStore.Domain/Entities/Brand.cs             |  22 [32m+[m
 src/NovaStore.Domain/Entities/Category.cs          |  20 [32m+[m
 src/NovaStore.Domain/Entities/Product.cs           |  36 [32m++[m
 src/NovaStore.Domain/NovaStore.Domain.csproj       |   9 [32m+[m
 .../DependencyInjection.cs                         |  28 [32m++[m
 .../NovaStore.Infrastructure.csproj                |  22 [32m+[m
 .../Configurations/BrandConfiguration.cs           |  32 [32m++[m
 .../Configurations/CategoryConfiguration.cs        |  29 [32m++[m
 .../Configurations/ProductConfiguration.cs         |  52 [32m+++[m
 .../20260926202756_InitialCreate.Designer.cs       | 206 [32m+++++++++[m
 .../Migrations/20260926202756_InitialCreate.cs     | 133 [32m++++++[m
 .../Migrations/NovaStoreDbContextModelSnapshot.cs  | 203 [32m+++++++++[m
 .../Persistence/NovaStoreDbContext.cs              |  26 [32m++[m
 .../Repositories/CategoryRepository.cs             |  41 [32m++[m
 .../Repositories/ProductRepository.cs              |  27 [32m++[m
 38 files changed, 1876 insertions(+)
